# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_text', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('puzzle_text', models.CharField(max_length=900)),
            ],
        ),
        migrations.AddField(
            model_name='clue',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle.Puzzle'),
        ),
    ]
