# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='answer',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
