# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_clue_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='start',
            new_name='start_num',
        ),
        migrations.AddField(
            model_name='clue',
            name='start_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clue',
            name='start_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
