# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-03-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='UUID',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
